name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: registry.cn-hangzhou.aliyuncs.com/dreamer2q/small-bobot
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USER }} # 用户名
          password: ${{ secrets.DOCKER_PASS }} # 密码
          dockerfile: Dockerfile
          snapshot: true

      - name: Deploy
        run: |
          # sleep 1
          curl -d "" ${{ secrets.WEBHOOK }}
