name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go Env
        uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: '1.16.3'

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -tags netgo -v -o main .

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: registry.cn-hangzhou.aliyuncs.com/dreamer2q/small-bobot
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USER }} # 用户名
          password: ${{ secrets.DOCKER_PASS }} # 密码
          dockerfile: Dockerfile
          snapshot: true

      - name: Deploy
        run: |
          # sleep 1
          curl -d "" ${{ secrets.WEBHOOK }}
